/**
 * Typed access to the regulatory graph generated by scripts/build-graph.mts.
 * Used by the /admin console (server) and X-ray mode (client). Pure functions;
 * no framework imports, so the graph is usable from tests and scripts too.
 */

import graphJson from "@/generated/graph.json";

export type NodeKind = "claim" | "safety" | "reference" | "page" | "component";
export type EdgeRel = "contains" | "supported_by" | "balanced_by" | "cites";

export interface GraphNode {
  id: string;
  kind: NodeKind;
  label: string;
  status?: string;
  number?: number;
  page?: string;
  route?: string;
  file?: string;
}

export interface GraphEdge {
  from: string;
  to: string;
  rel: EdgeRel;
  order?: number;
  locator?: string;
}

export interface Graph {
  generatedAt: string;
  counts: Record<string, number>;
  nodes: GraphNode[];
  edges: GraphEdge[];
  checks: {
    unapprovedInUse: string[];
    unknownObjectsInUse: string[];
    danglingRefs: string[];
    claimsWithoutEvidence: string[];
    unusedClaims: string[];
    unusedSafety: string[];
    looseRefsByPage: Record<string, number>;
    pagesConverted: string[];
  };
}

export const graph = graphJson as unknown as Graph;

const nodeIndex = new Map(graph.nodes.map((n) => [n.id, n]));
const outEdges = new Map<string, GraphEdge[]>();
const inEdges = new Map<string, GraphEdge[]>();
for (const e of graph.edges) {
  outEdges.set(e.from, [...(outEdges.get(e.from) ?? []), e]);
  inEdges.set(e.to, [...(inEdges.get(e.to) ?? []), e]);
}

export function getNode(id: string): GraphNode | undefined {
  return nodeIndex.get(id);
}

export function edgesFrom(id: string, rel?: EdgeRel): GraphEdge[] {
  return (outEdges.get(id) ?? []).filter((e) => !rel || e.rel === rel);
}

export function edgesTo(id: string, rel?: EdgeRel): GraphEdge[] {
  return (inEdges.get(id) ?? []).filter((e) => !rel || e.rel === rel);
}

export function kindOf(id: string): NodeKind {
  return id.split(":")[0] as NodeKind;
}

export function bareId(id: string): string {
  return id.slice(id.indexOf(":") + 1);
}

/** DOM attribute value → graph node id */
export function nodeIdFor(kind: "claim" | "safety" | "ref" | "component", value: string, route: string): string {
  if (kind === "component") return `component:${route}#${value}`;
  if (kind === "ref") return `ref:${value}`;
  return `${kind}:${value}`;
}

export interface Usage {
  component: GraphNode;
  page: GraphNode;
  order?: number;
  rel: EdgeRel;
}

/** Every component/page that contains (or loosely cites) a claim, safety object, or reference */
export function usagesOf(id: string): Usage[] {
  const rels: EdgeRel[] = kindOf(id) === "reference" ? ["contains", "cites"] : ["contains"];
  return edgesTo(id)
    .filter((e) => rels.includes(e.rel) && kindOf(e.from) === "component")
    .map((e) => {
      const component = getNode(e.from)!;
      const page = getNode(component.page ?? "")!;
      return { component, page, order: e.order, rel: e.rel };
    })
    .sort((a, b) => (a.page.route ?? "").localeCompare(b.page.route ?? "") || (a.order ?? 0) - (b.order ?? 0));
}

export interface TraceResult {
  root: GraphNode;
  references: GraphEdge[]; // root → ref (supported_by)
  safety: GraphEdge[]; // root → safety (balanced_by)
  supports: GraphEdge[]; // claim/safety → root, when root is a reference
  balances: GraphEdge[]; // claim → root, when root is safety
  usages: Usage[];
  contains: GraphNode[]; // when root is a component or page
  /** Every node id connected to the root (excluding the root) — what X-ray lights up */
  connected: Set<string>;
}

/**
 * Follow provenance and dependencies one hop in every direction:
 * "why is this here?" and "what depends on it?"
 */
export function trace(id: string): TraceResult {
  const root = getNode(id);
  if (!root) throw new Error(`Unknown graph node "${id}"`);

  const references = edgesFrom(id, "supported_by");
  const safety = edgesFrom(id, "balanced_by");
  const supports = edgesTo(id, "supported_by");
  const balances = edgesTo(id, "balanced_by");
  const usages = usagesOf(id);

  let contains: GraphNode[] = [];
  if (root.kind === "component") {
    contains = edgesFrom(id).filter((e) => e.rel === "contains" || e.rel === "cites").map((e) => getNode(e.to)!).filter(Boolean);
  } else if (root.kind === "page") {
    const comps = edgesFrom(id, "contains").map((e) => getNode(e.to)!).filter(Boolean);
    contains = [
      ...comps,
      ...comps.flatMap((c) => edgesFrom(c.id).filter((e) => e.rel === "contains" || e.rel === "cites").map((e) => getNode(e.to)!)),
    ].filter(Boolean);
  }

  const connected = new Set<string>();
  for (const e of [...references, ...safety]) connected.add(e.to);
  for (const e of [...supports, ...balances]) connected.add(e.from);
  for (const u of usages) {
    connected.add(u.component.id);
    connected.add(u.page.id);
  }
  for (const n of contains) connected.add(n.id);
  // A reference lights up the safety objects and claims that cite it; a claim
  // also lights up the references its balancing safety objects cite (one hop
  // further keeps the fair-balance chain visible).
  if (root.kind === "claim") {
    for (const e of safety) for (const se of edgesFrom(e.to, "supported_by")) connected.add(se.to);
  }
  connected.delete(id);

  return { root, references, safety, supports, balances, usages, contains, connected };
}

export function checksPassed(): boolean {
  const c = graph.checks;
  return (
    c.unapprovedInUse.length === 0 &&
    c.unknownObjectsInUse.length === 0 &&
    c.danglingRefs.length === 0 &&
    c.claimsWithoutEvidence.length === 0
  );
}
