/**
 * Pulls published claim wording from Supabase into
 * src/generated/published-overrides.ts, which src/data/claims.ts merges
 * over the baseline registries in src/data/governed.
 *
 * The baseline in git is version 1 of every claim. Anything approved and
 * signed since then lives in the database, so promotion needs no code change
 * and no terminal: approve → publish → deploy hook → this script runs → the
 * site rebuilds with the new wording.
 *
 * Runs in prebuild. Degrades to an empty override set when Supabase is not
 * configured or unreachable, so a build never fails because of it.
 */

import { writeFileSync, mkdirSync, existsSync, readFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = resolve(ROOT, "src/generated/published-overrides.ts");

interface Override {
  object_id: string;
  version: number;
  text: string;
  refs: unknown[];
  safety: string[];
  published_at: string;
  approval_seq: number;
}

/** .env.local for local builds; real env vars on Vercel */
function env(name: string): string | undefined {
  if (process.env[name]) return process.env[name];
  const file = resolve(ROOT, ".env.local");
  if (!existsSync(file)) return undefined;
  for (const line of readFileSync(file, "utf8").split("\n")) {
    const t = line.trim();
    if (t.startsWith("#") || !t.includes("=")) continue;
    const [k, ...rest] = t.split("=");
    if (k.trim() === name) return rest.join("=").trim();
  }
  return undefined;
}

function write(overrides: Override[], note: string) {
  mkdirSync(dirname(OUT), { recursive: true });
  // A .ts module rather than JSON: no import attributes, no path alias, so
  // both Next and plain `node` running the build scripts can read it.
  const body = `// Generated by scripts/fetch-published.mts — do not edit.
// ${note}
export interface PublishedOverride {
  object_id: string;
  version: number;
  text: string;
  refs: unknown;
  safety: unknown;
  published_at: string;
  /** the signature that authorised this wording */
  approval_seq: number;
}

export const fetchedAt = ${JSON.stringify(new Date().toISOString())};
export const overrides: PublishedOverride[] = ${JSON.stringify(overrides, null, 2)};
`;
  writeFileSync(OUT, body);
  console.log(`📝 published overrides: ${overrides.length} (${note})`);
}

const url = env("NEXT_PUBLIC_SUPABASE_URL");
const key = env("NEXT_PUBLIC_SUPABASE_ANON_KEY");

if (!url || !key) {
  write([], "Supabase not configured; baseline only");
} else {
  try {
    const res = await fetch(`${url.replace(/\/$/, "")}/rest/v1/published_claims?select=object_id,version,text,refs,safety,published_at,approval_seq&order=object_id`, {
      headers: { apikey: key, Authorization: `Bearer ${key}` },
      signal: AbortSignal.timeout(15000),
    });
    if (!res.ok) {
      write([], `Supabase returned ${res.status}; baseline only`);
    } else {
      const rows = (await res.json()) as Override[];
      write(rows, rows.length ? "merged over the baseline" : "none published yet");
    }
  } catch (e) {
    write([], `fetch failed (${e instanceof Error ? e.message : "unknown"}); baseline only`);
  }
}
